spring.jpa.open-in-view: false
spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: ${LANGUSTA_DB_MYSQL}:${LANGUSTA_DB_PORT}/${LANGUSTA_DB_NAME}
spring.datasource.username: ${LANGUSTA_DB_USERNAME}
spring.datasource.password:
