spring.jpa:
  open-in-view: false
  hibernate.ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
spring.datasource:
  url: jdbc:${LANGUSTA_DB_HOST}:${LANGUSTA_DB_PORT}/${LANGUSTA_DB_NAME}
  username: ${LANGUSTA_DB_USERNAME}
  password:
server:
  port: ${LANGUSTA_APPLICATION_PORT}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore/keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-alias: ${KEY-ALIAS}
trust.store: classpath:keystore/keystore.p12
trust.store.password: ${TRUSTSTORE_PASSWORD}
